[[fzf]]
arch = "aarch64"
git-tree-sha1 = "fe3bf078f02f8a9a87d65a81783f6934f4b0c234"
os = "macos"

    [[fzf.download]]
    sha256 = "75f251754aab4c434f702952de40817b6baf958ebad62e8cf39752bd6202d054"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.aarch64-apple-darwin.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "f977b437a5aefdc31814c184abcd964b36445056"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "f9432dc7e6919e8af2446de85a6c8199ccc53fe91bb0a3816f7e3ec084b4f61f"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.aarch64-linux-gnu.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "322d7d98551a51192ec7818b48911b67574a1b13"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "25d0e0c32db93d3b022c6cd879c8dd2b646e7c46bad69bab404fb04a7a501275"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.aarch64-linux-musl.tar.gz"
[[fzf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e8eddde279d4dba2a6d7c1dd12d495c69dadbb8b"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "2ece0281f6ab5d7713706b1788940c2d9dad03db5e99411e9090bee42709aad0"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.armv6l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4f8f33392a873a26ae90818e6b33013d9f6892e8"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "cb7af75c5805169e2d566398b1017d10f6de56b5a854653d58f40bb65d43f0ae"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.armv6l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b707c8eefd6431691c3202e0d148af047fe31df2"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "0a185cb50ac1584b7330dc6fa4339c4afd246a03e787905b126c896bbb3dd539"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.armv7l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8269d9563136c14dea3c82caa8760d66e5a98a9b"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "ba35792a2b9c744f0486439d2065342737867c62ff5c786d39d7c9521555115f"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.armv7l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "61f9e7a66c7896446d0aa2862225d03f1cc62204"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "b9c0aa2f3205e712163f8b1dbaec1fddc470cc32ecb3e58a808a54508fbedc08"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.i686-linux-gnu.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "2e21734fbfa94e1ff5eb6c0abf203d7794601de3"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "eb3b688f64ab4e40ea0c45455a6cb2f3619f4e52ce17049511d296a23782330f"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.i686-linux-musl.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "de8f5c98410139f5844e2b809c1241db29e925a3"
os = "windows"

    [[fzf.download]]
    sha256 = "47e24fc948802b4c2d348ad2bddccdd5e91beec14eabfdb5c12802d08d2e888b"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.i686-w64-mingw32.tar.gz"
[[fzf]]
arch = "powerpc64le"
git-tree-sha1 = "b32a6c6353cf0821b12d902f5463b4315eb44816"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "3a5d421f6a902d9549218adba98c045771b5a9ba4fb01b18b01ff14a5b181334"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.powerpc64le-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "d4c66c83a479b830a9efd9f3e2381c225566eddc"
os = "macos"

    [[fzf.download]]
    sha256 = "7acc73d62d097cf8d2def72889729d77718d4eceb02119f30c3fdf9594e4a997"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.x86_64-apple-darwin.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "54d8233ce0b77c7c0b975feb1d75bea355b90fe5"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "9e4bd3a396e80a7671d769d61db76e4c40c657979fada30c8358f226be7a3f64"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.x86_64-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "cf4faf10cf17ef7666981b1ae7d6d4db1f521ea9"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "0dc4f7b3ebacce51227ad9a79b4ced39cbfd9c24a255cd2a278ecdad4c3d0ac8"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.x86_64-linux-musl.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "08c6e33a42e32efd7d78c3275c25e63f3cc4ae9e"
os = "freebsd"

    [[fzf.download]]
    sha256 = "56065e73c2254f583b403b0532b866c775e41c761533c4ba0aa30cf05d218013"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.x86_64-unknown-freebsd.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "359e1c31ad2a4de22eda67c19e32dc31f84061ce"
os = "windows"

    [[fzf.download]]
    sha256 = "6fdc7bbaaaa82ba181c051e72515216671a0b205346f8117e29bd446eca7a45c"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.28.0+0/fzf.v0.28.0.x86_64-w64-mingw32.tar.gz"
