[[fzf]]
arch = "aarch64"
git-tree-sha1 = "9503c7ff32c675d80241794272926225b53955ac"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "6b80d379719af362114a76ed0161489a4ab6923e54dff81360e2d3f2179263df"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.aarch64-linux-gnu.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "259b6b2adb90850a6b51778cabe6b616f1102a62"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "f01c14a427c859df4a274ed2370a845a6bd0e365534d0bd4d971cf8615cda37a"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.aarch64-linux-musl.tar.gz"
[[fzf]]
arch = "armv7l"
git-tree-sha1 = "54898756af9cfaacafb52e286f5bf169f1dd19f7"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "8deff7fcbb094135880c36482550e7db66c36131fa89b608f4faa795a3374739"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.armv7l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv7l"
git-tree-sha1 = "3f38fe65d0c83011a5b7633bbbb0165821f3776d"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "0c31d8452f6a02ec9543f27005844ba065ccf7f5c949b34b878549cc35d69305"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.armv7l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "6e1d10f59300918abf2027746f73319371081b2a"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "7fbf1acb3e19f0d493cef21f5ec8bcd803ee0f625d664cb86d0956d7acecf078"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.i686-linux-gnu.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "0f99ec70306316c1826649f593eff223eeea1896"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "3b8bbea9c034048ab027b131d063dda83cd2377ef4f71809ebc9090f8d24e6e2"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.i686-linux-musl.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "009c8cbf90c14cd39f108e8dcb46b55fa9876f89"
os = "windows"

    [[fzf.download]]
    sha256 = "577173ebd74a716010ba3e06703141f67dc8f9f6065dd100a865a467795e6aa4"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.i686-w64-mingw32.tar.gz"
[[fzf]]
arch = "powerpc64le"
git-tree-sha1 = "f624b0693a44e9888b9aa90b05459fed345fac05"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "032756a7cb60ba1ac9ce6db43a8beb97b639c34a0932b506a5833c33b15fa574"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.powerpc64le-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "ee9ae5d166616fa3d945cc775f6c8e0aba743bd8"
os = "macos"

    [[fzf.download]]
    sha256 = "ffe0fce79fc5b934e953427b951c15e2a6c25a4a33daa0cbdb50023fdaa2c3ac"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.x86_64-apple-darwin14.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "0927b05968460a4b71d12bdcc8f63ccdfb316a65"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "790f987a8e4edd7129263bb2ec1c7e2379ce6c8e3f0e08b07c2c944b9fa7cf44"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.x86_64-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "27017072b8a28dcb7a6ca0d924ff6bb81bf0faa9"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "3ec168e0f39e56ec337a82267aaa4d3a9284d3416dd5086c72cd9d84a1f0b8a3"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.x86_64-linux-musl.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "72d2165ff26c1a7a428abbf3d3e262d26cd0b960"
os = "freebsd"

    [[fzf.download]]
    sha256 = "7583adca834f51979c0ee87e606b2a9608717e37cc53ecc25c07023f22dd4bca"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.x86_64-unknown-freebsd11.1.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "1737da76620ebeeccfa5408b924e19043cfd2124"
os = "windows"

    [[fzf.download]]
    sha256 = "1cb8f21cace16f81af8b85e6c1d3642065f5e449ba52e09b0c4c57f466e1a6bd"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.21.1+0/fzf.v0.21.1.x86_64-w64-mingw32.tar.gz"
