[[fzf]]
arch = "aarch64"
git-tree-sha1 = "c532bae0e1154c183a0316ace94353a252ffd036"
os = "macos"

    [[fzf.download]]
    sha256 = "0171eff8e6e8b395b5b4a11a23268ad15bdcdd6fe62b60b483e9fa15011db91f"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.aarch64-apple-darwin.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "e1fbbcd3d0d3a11fc2831ab5568f0ad8f3fde739"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "301ec3090fc169948fed587936343abf6018d56c6566f7c9b7710f7c9f87bede"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.aarch64-linux-gnu.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "e1fbbcd3d0d3a11fc2831ab5568f0ad8f3fde739"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "301ec3090fc169948fed587936343abf6018d56c6566f7c9b7710f7c9f87bede"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.aarch64-linux-musl.tar.gz"
[[fzf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bad06e2da73b6c2d141e0ecd9e21ed490ed381da"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "b8a5b57c250fffa669535ee70600ef245ea4f8a25cec8c46e7fbedb7dae4d39e"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.armv6l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bad06e2da73b6c2d141e0ecd9e21ed490ed381da"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "b8a5b57c250fffa669535ee70600ef245ea4f8a25cec8c46e7fbedb7dae4d39e"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.armv6l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a240491caa5b440fbf4ebd5fe556f4f0adc88306"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "1853a786861ba194410a5fc8855043d5190414999b79db7c7ea42aefaf7fa985"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.armv7l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a240491caa5b440fbf4ebd5fe556f4f0adc88306"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "1853a786861ba194410a5fc8855043d5190414999b79db7c7ea42aefaf7fa985"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.armv7l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "5fd5a0ac13a738d5b2e5f3eabe04134ac6aa67fb"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "40860406916e442d6ffa1b2a9ce37753d260d43a0c08fdef3bc7764fbca80411"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.i686-linux-gnu.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "5fd5a0ac13a738d5b2e5f3eabe04134ac6aa67fb"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "40860406916e442d6ffa1b2a9ce37753d260d43a0c08fdef3bc7764fbca80411"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.i686-linux-musl.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "9d2643bf27dc4fc19c17ce73c0828e6162d075ab"
os = "windows"

    [[fzf.download]]
    sha256 = "425faeb6587773b35ea3fa3badf3e8a0f5eaa15b88d7598f866187c41c3fb760"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.i686-w64-mingw32.tar.gz"
[[fzf]]
arch = "powerpc64le"
git-tree-sha1 = "8c1165443e46f34e7e1f613545e7c7ac90cea904"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "6233f0066c429ee56409ded02b10674b27d20122fce7b687fe1aa08654519b25"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.powerpc64le-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "54028507427511a3f37024cba197c4755e4ac42f"
os = "macos"

    [[fzf.download]]
    sha256 = "0f1c02a38803bdf3ce4773681a78945cef9db1c6c6726b10d7903083de25e86d"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.x86_64-apple-darwin.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "df13aacf2ce8acfb50da6f4c60d96b254a19c946"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "4e58a7cc2cc6659a84ea4aaa1da1bb866a0ff9331e3d131a88f0c43d3686945d"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.x86_64-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "df13aacf2ce8acfb50da6f4c60d96b254a19c946"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "4e58a7cc2cc6659a84ea4aaa1da1bb866a0ff9331e3d131a88f0c43d3686945d"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.x86_64-linux-musl.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "8a00d6ba57bb4c369c70b8fac8b8042dde8975b3"
os = "freebsd"

    [[fzf.download]]
    sha256 = "348e834e48522a007d0d3ddbf152a2e16b53edf5ef7a886aedc9aa6624446b15"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.x86_64-unknown-freebsd.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "2ecdfd28aa68e373b781e33c15bb1635426ea6b8"
os = "windows"

    [[fzf.download]]
    sha256 = "d12ae328ad084fc99ae9435c1371adb8954a6cf0f62d25dde307ac0f42a2168f"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.35.1+0/fzf.v0.35.1.x86_64-w64-mingw32.tar.gz"
