[[fzf]]
arch = "aarch64"
git-tree-sha1 = "91b8cd7242875ecb211f2dff63f8c0d37e70879e"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "018eecedfbacc135883224580da45e1dd2fb8fa6ea12c25e4f582b5fceab6f35"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.aarch64-linux-gnu.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "b2427ae64264c81f4cb03a108e44dad737cefc0b"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "377f80140c630c142b367b87559a365d42021e3db94ed34f722c8ab9ded72fe8"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.aarch64-linux-musl.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ff8d3d3f60e803a2c78905a941284b2542de1f11"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "6292192d726baceb6d4d0a5904a0ef63b86a5a61304b3a13ba0bd3fbb17bad6a"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.armv7l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44128328d4b1c432386060ececa77ab31d481d62"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "ed6765913f7367621fbd1e611055c5b9032b90765b0f285a028abda2c7bb6e5f"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.armv7l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "b2e658dc921bf7fd4ec44d46ccc9cf99cf50f1dc"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "1c1a571d7e10986ab8199f8932e8ce8ebaca094a889f99e8dc50015d71e239eb"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.i686-linux-gnu.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "4f1cefa5c3476e01da9180c9306a0f7b43690146"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "c8fe9fe97dc96328d8ae8627ba8816f4b26e77e2c694303cb32bdbf121429fd6"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.i686-linux-musl.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "113ddb1455c3108a150b50a83a41fe0d171759bd"
os = "windows"

    [[fzf.download]]
    sha256 = "1be20e867bcf95816dcd65fcd27108b416837fad7835d8b434215769204b6485"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.i686-w64-mingw32.tar.gz"
[[fzf]]
arch = "powerpc64le"
git-tree-sha1 = "1d5db5428e8a99c48d2f27db0f1c64f523dbce64"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "09034810c47fe4bdd9a036713fa6bcfc86bf2d1405b34f81173ec694924122c2"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.powerpc64le-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "88aeed19eb8fec3156f542334a704599a37814b2"
os = "macos"

    [[fzf.download]]
    sha256 = "8c00c7b272a9e208e9aa62b187e5a76d32c9bfb5577688f0a74ffc4e86e1a8ea"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.x86_64-apple-darwin.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "f5c2380fa421645ff4c9e7e67e919db49331580c"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "7f3bd99b36da68374a271f6f72c65448032088b56cd8de95a23027a52e0a6e4e"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.x86_64-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "87388be433733972af3772fbd9e0051f113e231b"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "27ac76837d392352bdf1abe34c0d1f040ef97a9354ab2c63c65a264c4f34c077"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.x86_64-linux-musl.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "bb26a9232dcf3124421ef0f3f8283cd68a6e0303"
os = "freebsd"

    [[fzf.download]]
    sha256 = "71df22b1fe6b2a4a34600f8e793ac8acf84c3c43d4de535d0e93521a28f14635"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.x86_64-unknown-freebsd.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "ea7f89af072e8ea021192eeea77f1cbe8a02e8d1"
os = "windows"

    [[fzf.download]]
    sha256 = "705a1dcb07911ba3efcab53a42fb28b39396915ab5d48a4c6d86fb397584b0d2"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.24.4+0/fzf.v0.24.4.x86_64-w64-mingw32.tar.gz"
