[[fzf]]
arch = "aarch64"
git-tree-sha1 = "9efc5a8b42127de4b70bf84c0bdc7566c8c480f0"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "a9a2764c156a50cd00ba8426625598fb2f11ed16c7366086b4126babe8912f6c"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.aarch64-linux-gnu.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "bc028861d3b951c688e73688316ba5e2d93c2c4e"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "373dc2389a2329fda83fd541cc54a19cc9bd98e7248350270566066a992b3367"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.aarch64-linux-musl.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e801d17a498b21d96536fa37bb3bb8f857e3da08"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "0f1be14f20f49bcc60bc537ea07f8ce9a659dcb7abe140d58437bcfd62d4ae70"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.armv7l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a4b4a9a3497352b0a09b49c2b461d7243ed78b6"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "17598af21c6e5c201aa09fb223a21977f3b3dae5be460032626fa24b200e84a5"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.armv7l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "4646ff4b9609160ac1007a8bdb7d1f091b5e0b97"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "32dd7e5beba0b98f82b5b426e0cbb635f4cc0cd0d9b488eed62f81e01e06ad6b"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.i686-linux-gnu.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "94c5abc266307840897c7a82c6c26dc92dad4972"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "c547b46caaae61ee3c132f46e4918415af597a3721356a44537fd992b476c4cf"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.i686-linux-musl.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "0c1eac616b5f3f2a8f25f6c8f270c6aecea6ce07"
os = "windows"

    [[fzf.download]]
    sha256 = "18bfb06e9e060e97565b7f79b26bd24ccb7ab525bc23f6c8aa3d9f93e361c555"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.i686-w64-mingw32.tar.gz"
[[fzf]]
arch = "powerpc64le"
git-tree-sha1 = "0487eccdbc626a9a361f6c9f17a750aeed6c6f53"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "917d922923e949b89aa4f9ac97293e52c47ac0bbc3ffc5369c46373ba90dc7aa"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.powerpc64le-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "2f9315cf2375a6b8008129cd77fbdd6054bf4ddd"
os = "macos"

    [[fzf.download]]
    sha256 = "b9b455119c61b97dbf18d5099480c37f7874f6da7b4ea0dc4ab76d89e6c8b0db"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.x86_64-apple-darwin.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "22e953e7da13ab0e0c3c917e6366ade691a07e3a"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "e02d346ddcf78c9c45cca15fbd1a2e94bbcf97f9d8027a252a5741b1758feb2b"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.x86_64-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "5f61e086e95b304ece2711ce055150d462749676"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "df9b692a00f4c56d6a3a99c38c5f2cd596272bd8194cb6dca0041ddea71d4967"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.x86_64-linux-musl.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "cafcb70101d436c57fe9d89f874bf86e16bd9969"
os = "freebsd"

    [[fzf.download]]
    sha256 = "5e6c966439ea569a05ebd3660cf7761b8a53f44b17bdfe358e8ce8b813861729"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.x86_64-unknown-freebsd.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "87dace4a4dcac70b695957012aabfb4012bd2eb4"
os = "windows"

    [[fzf.download]]
    sha256 = "84016583190dd158515ef88fed1f089a9d382614970b01a0799b0ec4cf91e244"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.25.0+0/fzf.v0.25.0.x86_64-w64-mingw32.tar.gz"
