[[fzf]]
arch = "aarch64"
git-tree-sha1 = "7c355a58635f20ae72c33884353863cb5288ada5"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "9f125c8b8ed9c35271fbc342aaab7987b4ed2cefa94ba0902022af5ee6e4e39d"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.aarch64-linux-gnu.tar.gz"
[[fzf]]
arch = "aarch64"
git-tree-sha1 = "ad179db29e8e4f1f2f69119d18a15cc13cf6c4ed"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "9907b65436e3f61d6c97ce43d17595b00f650f020b6d4fc45c0fbad49e07bf58"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.aarch64-linux-musl.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1231845b725dd029c46eaf5879cf57ddfeb6eccc"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "be223a520b3a0dcfc2db0914ae073362efa1b79377bfe2f496113fe5e69f78f6"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.armv7l-linux-gnueabihf.tar.gz"
[[fzf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "306104f727c85b3ea44cc58350bbc2dad3c71648"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "5bc0369b47946111f66ac86e34ab8e133817b7ad1b86812246cbbfb465ca844e"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.armv7l-linux-musleabihf.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "8d0950503749c553ff226d0680676b128aa718c3"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "e522222642e61568a30b492a78b06eba105176a9e1f05da61416ce2d9dbd3e5d"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.i686-linux-gnu.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "8a04b696e2c67ee16a256b1c463ee736650f9f8e"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "748873d54e65bae745784b303d8140187bf07e1caee01de243bbb78efb4f2989"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.i686-linux-musl.tar.gz"
[[fzf]]
arch = "i686"
git-tree-sha1 = "afd74f98908a337b5312f5a1e151a4b1f6618ea8"
os = "windows"

    [[fzf.download]]
    sha256 = "2d878e3b2f2d5dc3d8e931cebfe723b2e50414fda2872597641cfa9b9a817bff"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.i686-w64-mingw32.tar.gz"
[[fzf]]
arch = "powerpc64le"
git-tree-sha1 = "ecf016557ac3512a510cd1b2db8cb3c9f9ae74d8"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "5912f96a5a586d6d694a0665ff38986fde3b9f9de0030762d2713c5f50bff9da"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.powerpc64le-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "73a8601a0539c899a4f18ca97696db5ad62c1a32"
os = "macos"

    [[fzf.download]]
    sha256 = "32efdbdd7101743674ffedb6e7fe9913f5dc60e6e56f0abdeb55e2a362c0312c"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.x86_64-apple-darwin.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "473323b83dcddc050062cce04421d67f29ff6d4c"
libc = "glibc"
os = "linux"

    [[fzf.download]]
    sha256 = "f78805be86a2648481e76bb5c61a3ad397a6054f2166603069cb2c0da62163a3"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.x86_64-linux-gnu.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "90af057ccd7b8b29a1a0192bb11dc0f0322b9cfe"
libc = "musl"
os = "linux"

    [[fzf.download]]
    sha256 = "5b399b4b0cb078a2074a69474f46b8761997233e2bcacdc99742f504e8fb0123"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.x86_64-linux-musl.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "3485fbe73cab198ee0b321255b64a08b70bf3e12"
os = "freebsd"

    [[fzf.download]]
    sha256 = "3ac0954e8a413a198bf14a7ab22a0ed54a2900984d9625555e011dd7f5dca402"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.x86_64-unknown-freebsd.tar.gz"
[[fzf]]
arch = "x86_64"
git-tree-sha1 = "463605bb7c637d409f6be6fe8fb7458f781b54a7"
os = "windows"

    [[fzf.download]]
    sha256 = "3f6e35d7ba5823a495ce8fd4920a26bbcdb37b0c7d9227a65bb832772c39328c"
    url = "https://github.com/JuliaBinaryWrappers/fzf_jll.jl/releases/download/fzf-v0.23.1+0/fzf.v0.23.1.x86_64-w64-mingw32.tar.gz"
